### ISSUE TITLE
can't load up weekly review in chrome

### ISSUE THREAD

**Issue by iros** [bocoup/nest-weekly-review#117] opened 2015-09-28 20:17 UTC
![image](https://cloud.githubusercontent.com/assets/18690/10147525/6de3e944-65fc-11e5-8fb2-2494274a679b.png)

**Comment by jugglinmike** [comment] 2015-09-28 21:39
Thanks for the report, Irene! This was caused by a conflation of circumstances (what else is new) triggered by moving this server behind the still-under-development SSL terminator. If you're curious, you can read about it in the commit that fixes it:

a8e94ac9c9d96da7dfdc74fef1c84357d02fdde9

Anyways, we're all set now!

**Closed by jugglinmike** 2015-09-28 21:39 UTC
Labels: bug
